apiVersion: apps/v1
kind: Deployment
metadata:
  name: sps-deployment
  labels:
    app: sps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sps
  template:
    metadata:
      labels:
        app: sps
    spec:
      containers:
      - name: sps-container
        image: pnander/springboot-docker:1.0
        ports:
        - containerPort: 8090