apiVersion: v1
kind: Service
metadata:
  name: sps-service
spec: 
  type: NodePort
  selector:
    app: sps
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30100
